version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: >
      sh -c  "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    container_name: btc-api
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - "5672:5672"
  worker:
    build: .
    command: sh -c "celery -A core.celery worker --loglevel=info -B"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    restart: on-failure
volumes:
  postgres_data: